### ISSUE TITLE
fieldSeparator property not working

### ISSUE THREAD

**Issue by ZeroKaa** [alexcaza/export-to-csv#96] opened 2024-04-08 09:07 UTC
**Describe the bug**
I try to replace the default fieldSeparator by ";" but the output still use ","

**To Reproduce**

const config = mkConfig(
  {
    useKeysAsHeaders: true,
    fieldSeparator: ";",
    showColumnHeaders: false,
    filename : "xxxxxxxxx.xsv"
  }
);

download(config)(data);

**Expected behavior**
I expect the downloaded file to have field separated by a ";"

**Comment by alexcaza** [comment] 2024-04-10 00:36
Could you share which version of the library and which browser(s) you're running? I can't replicate this behaviour.

Here's a stackblitz example running `v1.2.4`: https://stackblitz.com/edit/vitejs-vite-e1whts?file=src%2Fmain.ts

**Comment by alexcaza** [comment] 2024-04-29 19:06
I'm going to close this for now since I can't reproduce it. If the issue persists or comes back, feel free to open another issue with more details 😄

**Closed by alexcaza** 2024-04-29 19:06 UTC
Labels: bug
