### ISSUE TITLE
Column headers row are removed blank spaces also on the first row of csv

### ISSUE THREAD

**Issue by makiBaraba** [alexcaza/export-to-csv#101] opened 2024-04-22 21:36 UTC
When I generate csv, first two rows (if `showColumnHeaders: true`) or first row if `showColumnHeaders: false` is removed all blank spaces from string.
[products (4).csv](https://github.com/alexcaza/export-to-csv/files/15068806/products.4.csv)

**Comment by alexcaza** [comment] 2024-04-23 14:13
Which version of the library are you running @makiBaraba?

I tested this with v1.2.4, and the output is as expected—with spaces in tact.

I added some test cases (#102) to catch any possible regressions in the future, but you can see the CI tests passed without change to the library code.

Here's the action complete if you'd like to check: https://github.com/alexcaza/export-to-csv/actions/runs/8801913483/job/24156419369

There's also this Stackblitz using v1.2.4 if you'd like to see the output yourself: https://stackblitz.com/edit/vitejs-vite-u9lsey?file=src%2Fmain.ts

**Comment by makiBaraba** [comment] 2024-04-28 08:41
It seems that it works with download function, I try to implement it inside chrome extension mechanism, and use chrome.downloads API and this error ocurred.

**Comment by alexcaza** [comment] 2024-04-29 15:50
Gotcha! Thanks, @makiBaraba. I'm not familiar with that part of the extensions API. I'll see if I can reproduce it in a reduced test case when I can and get back to you.

**Comment by alexcaza** [comment] 2024-04-29 19:59
@makiBaraba I created a repo with a simple Chrome extension that uses the `chrome.downloads` API and `export-to-csv`. I can't reproduce the issue.

Link to repo: https://github.com/alexcaza/chrome-ext-reduced-test-case

Feel free to share more details; like the version of `export-to-csv` you're running. If you can link to the code of your project, that would be even better!

**Comment by alexcaza** [comment] 2024-05-14 15:22
I'm going to close this issue since OP hasn't responded and I can't reproduce it. Feel free to open another issue with more details if it still isn't resolved 😄

**Closed by alexcaza** 2024-05-14 15:22 UTC
Labels: bug
